package cli

import (
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"sort"
	"strings"
	"text/tabwriter"

	"github.com/jjsanda/genai-otel-ingest-conformance/internal/engine"
	"github.com/jjsanda/genai-otel-ingest-conformance/internal/registry"
	"github.com/jjsanda/genai-otel-ingest-conformance/internal/rules"
)

const rulesUsage = `Inspect the conformance rule catalog.

Usage:
  genai-conformance rules list [flags]

Flags:
`

// runRules dispatches the rules subcommands. `rules list --format markdown`
// is the single source of docs/rules.md (regenerated by make docs and
// checked in CI), so the catalog documentation can never drift from the
// code.
func runRules(args []string, stdout, stderr io.Writer) int {
	if len(args) == 0 || args[0] != "list" {
		fmt.Fprint(stderr, rulesUsage)
		return ExitUsage
	}
	fs := flag.NewFlagSet("rules list", flag.ContinueOnError)
	fs.SetOutput(stderr)
	format := fs.String("format", "table", `output format: "table", "markdown", or "json"`)
	fs.Usage = func() {
		fmt.Fprint(stderr, rulesUsage)
		fs.PrintDefaults()
	}
	if err := fs.Parse(args[1:]); err != nil {
		return ExitUsage
	}

	reg := registry.Default()
	catalog := engine.New(reg, rules.All(reg)...).Rules()

	switch *format {
	case "table":
		writeRuleTable(stdout, catalog)
	case "markdown":
		writeRuleMarkdown(stdout, reg, catalog)
	case "json":
		type entry struct {
			ID       string          `json:"id"`
			Severity engine.Severity `json:"severity"`
			Brief    string          `json:"brief"`
			DocURL   string          `json:"doc_url"`
		}
		out := make([]entry, 0, len(catalog))
		for _, r := range catalog {
			out = append(out, entry{ID: r.ID(), Severity: r.Severity(), Brief: r.Brief(), DocURL: r.DocURL()})
		}
		enc := json.NewEncoder(stdout)
		enc.SetIndent("", "  ")
		if err := enc.Encode(out); err != nil {
			fmt.Fprintf(stderr, "genai-conformance rules: %v\n", err)
			return ExitUsage
		}
	default:
		fmt.Fprintf(stderr, "genai-conformance rules: unknown format %q (want table, markdown, or json)\n", *format)
		return ExitUsage
	}
	return ExitOK
}

func writeRuleTable(w io.Writer, catalog []engine.Rule) {
	tw := tabwriter.NewWriter(w, 2, 4, 2, ' ', 0)
	fmt.Fprintln(tw, "ID\tSEVERITY\tCHECKS FOR")
	for _, r := range catalog {
		fmt.Fprintf(tw, "%s\t%s\t%s\n", r.ID(), r.Severity(), r.Brief())
	}
	_ = tw.Flush()
}

// ruleCategories maps ID prefixes to catalog sections, in display order.
var ruleCategories = []struct {
	prefix string
	title  string
	blurb  string
}{
	{"GENAI-SPAN-", "Span rules", "Checked streaming, per span, as telemetry arrives."},
	{"GENAI-TRACE-", "Trace-topology rules", "Checked per assembled trace (the gateway's closed windows, or the full input offline): request → agent → tool → retrieval → LLM continuity."},
	{"GENAI-METRIC-", "Metric rules", "Checked per metric: instrument shapes, units, required attributes, bucket advice."},
	{"GENAI-EVENT-", "Event rules", "Checked per GenAI log record, including evaluation results."},
	{"GENAI-RES-", "Resource rules", "Checked once per resource that emits GenAI telemetry."},
}

func writeRuleMarkdown(w io.Writer, reg *registry.Registry, catalog []engine.Rule) {
	fmt.Fprintln(w, "# Conformance rule catalog")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "<!-- GENERATED FILE — do not edit. Regenerate with `make docs`")
	fmt.Fprintln(w, "     (runs `genai-conformance rules list --format markdown`). -->")
	fmt.Fprintln(w)
	fmt.Fprintf(w, "%d rules, pinned to [open-telemetry/semantic-conventions-genai@`%s`](%s/tree/%s) (%s).\n",
		len(catalog), reg.Meta.SHA[:12], reg.Meta.Repo, reg.Meta.SHA, reg.Meta.Date)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Severity mapping: **ERROR** violates a Required (or decidable Conditionally")
	fmt.Fprintln(w, "Required) convention — the telemetry is broken for standards-based consumers;")
	fmt.Fprintln(w, "**WARNING** violates a Recommended (SHOULD) convention; **INFO** is a hint about")
	fmt.Fprintln(w, "legal-but-noteworthy telemetry. The conformance score counts ERROR- and")
	fmt.Fprintln(w, "WARNING-level checks; INFO never affects it.")

	for _, cat := range ruleCategories {
		var section []engine.Rule
		for _, r := range catalog {
			if strings.HasPrefix(r.ID(), cat.prefix) {
				section = append(section, r)
			}
		}
		if len(section) == 0 {
			continue
		}
		sort.Slice(section, func(i, j int) bool { return section[i].ID() < section[j].ID() })
		fmt.Fprintf(w, "\n## %s\n\n%s\n\n", cat.title, cat.blurb)
		fmt.Fprintln(w, "| ID | Severity | Checks for |")
		fmt.Fprintln(w, "|---|---|---|")
		for _, r := range section {
			fmt.Fprintf(w, "| [%s](%s) | %s | %s |\n", r.ID(), r.DocURL(), r.Severity(), r.Brief())
		}
	}
}
